module.exports.types = {
  media: ["mp4", "mkv"],
  archives: ["zip", "7z", "rar", "tar", "gz", "ar", "iso", "xz"],
  document: [
    "pdf",
    "doc",
    "dox",
    "xls",
    "xlsx",
    "odt",
    "ods",
    "odp",
    "odg",
    "odf",
    "txt",
    "ps",
    "tex",
  ],
  image: ["png", "jpeg", "jpg"],
};
